package com.example.crossds.controller;

import com.example.crossds.business.*;
import com.example.crossds.repository.AccountPlaylistRepository;
import com.example.crossds.repository.AccountRepository;
import com.example.crossds.repository.CollaborativePlaylistRepository;
import com.example.crossds.repository.TrackRepository;
import com.example.crossds.service.ApiResponseWrapper;
import com.example.crossds.service.Credentials;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.stream.Collectors;

@org.springframework.stereotype.Controller // This means that this class is a Controller
@RequestMapping(path="/api/playlist") // This means URL's start with /demo (after Application path)
public class PlaylistController extends MainController {

    private Logger logger = LoggerFactory.getLogger(PlaylistController.class);

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountRepository;

    @Autowired
    private AccountPlaylistRepository accountPlaylistRepository;

    @Autowired
    private CollaborativePlaylistRepository collaborativePlaylistRepository;

    @Autowired
    private TrackRepository trackRepository;

    @PostMapping(path="/{title}") // Map ONLY POST Requests
    public @ResponseBody Boolean createNewPlaylist (@PathVariable String title , @RequestBody List<Long> ids) {
        List<Account> accounts = accountRepository.findAllById(ids);

        CollaborativePlaylist collaborativePlaylist = new CollaborativePlaylist();
        collaborativePlaylist.setName(title);

        //pour chaque compte
        //  creation de la playlist sur la plateforme
        //  Objtenir l'id de la dite playlist
        //  Creation de l'account playlist + id playlist + account + collaborative playlist
        //save collaborative playlist

        for (Account account: accounts) {

            ApiResponseWrapper<String> id = getApiServiceFor(account).createPlaylist(account.getCredentials(), account.getUsername(), title);

            AccountPlaylist accountPlaylist = new AccountPlaylist();
            accountPlaylist.setService_playlist_id(id.getData());
            accountPlaylist.setCollaborativePlaylist(collaborativePlaylist);
            accountPlaylist.setAccount(account);
            accountPlaylistRepository.save(accountPlaylist);

            // The credentials have to be updated if changed
            Account tmp = new Account(account);
            tmp.setCredentials(id.getCredentials());
            accountRepository.save(tmp);
        }

        //if we get there, then the creation was a success
        return true;
    }

    @PostMapping(path="/update/{id}")
    public @ResponseBody boolean updateOne(@PathVariable Long id){


        //Part 1 - Update all new songs in to DB
        //Step 1.1 - Check which remote playlist were changed (snapshotHash)
        //Step 1.2 - Get All songs from those changed
        //Step 1.3 - Add all new Tracks in db

        //Part 2 - Update each remote playlist
        //Step 2.1 - All tracks from db not in remote playlist are appended to the add List

        Optional<CollaborativePlaylist> optionalCollaborativePlaylist = collaborativePlaylistRepository.findById(id);
        if(optionalCollaborativePlaylist.isPresent()) {
            CollaborativePlaylist collaborativePlaylist = optionalCollaborativePlaylist.get();

            //Part 1 - Update all new songs in to DB
            //get common tracks
            Set<Track> storedCommonTracks = collaborativePlaylist.getTracks();
            // for each platform
            Set<AccountPlaylist> accountPlaylists = collaborativePlaylist.getAccountPlaylists();
            for (AccountPlaylist ap : accountPlaylists) {
                //  get distant tracks
                ApiResponseWrapper<Set<Track>> distantTracks = getApiService(ap.getAccount().getPlatform())
                        .getPlaylistTracks(ap.getAccount().getCredentials(), ap.getService_playlist_id());
                //  only keep new tracks
                distantTracks.getData().removeAll(storedCommonTracks);
                //  for each track left :
                for (Track track: distantTracks.getData()) {
                    // get identifier for other platforms
                    Track newTrack = getAlternativeIdentifier(track);
                    trackRepository.save(newTrack);
                    storedCommonTracks.add(newTrack);

                }
            }
            collaborativePlaylist.setTracks(storedCommonTracks);
            collaborativePlaylistRepository.save(collaborativePlaylist);

            //Part 2

            Set<AccountPlaylist> updatesAP = new HashSet<>();
            Set<Account> updatesA = new HashSet<>();
            for (AccountPlaylist accountPlaylist : accountPlaylists) {
                Set<Track> newTracksToAdd = new HashSet<>(storedCommonTracks);
                Account modifyAccount = new Account(accountPlaylist.getAccount());
                AccountPlaylist modifyAccountPlaylist = new AccountPlaylist(accountPlaylist);

                Platform platform = accountPlaylist.getAccount().getPlatform();
                Credentials credentials = accountPlaylist.getAccount().getCredentials();
                String playlistId = accountPlaylist.getService_playlist_id();

                //Step 2.1
                // get new tracks for this account and create a list of its ids
                ApiResponseWrapper<Set<Track>> distantTracks = getApiService(platform).getPlaylistTracks(credentials, playlistId);
                credentials = distantTracks.getCredentials();

                //only add new tracks not in distant playlist
                newTracksToAdd.removeAll(distantTracks.getData());

                if(newTracksToAdd.size()>0){
                    List<String> tracksIds = newTracksToAdd.stream().map(track -> {
                        if(platform.equals(Platform.SPOTIFY) && track.isSpotify_availability()){
                            return track.getSpotify_identifier();
                        }
                        if(platform.equals(Platform.DEEZER) && track.isDeezer_availability()){
                            return track.getDeezer_identifier();
                        }
                        return null;
                    }).filter(Objects::nonNull).collect(Collectors.toList());

                    if(tracksIds.size()>0){
                        ApiResponseWrapper<String> response = getApiService(platform).addTracksToPlaylist(credentials, playlistId, tracksIds);
                        credentials = response.getCredentials();
                        modifyAccountPlaylist.setSnapshotHash(response.getData());
                    }
                }

                //save account's credentials
                modifyAccount.setCredentials(credentials);
                accountRepository.save(modifyAccount);

                //add modified accountPlaylist to the update list
                updatesAP.add(modifyAccountPlaylist);
            }

            updatesAP.forEach((ap)->{
                accountPlaylistRepository.save(ap);
            });
        }else{
            return false;
        }
        return true;
    }

    @PostMapping(path="/update")
    @Scheduled(fixedRate = 3600000) //Every hour
    public @ResponseBody void updateAll(){

        logger.info("Function : updateAll");

        Iterable<CollaborativePlaylist> collaborativePlaylists = collaborativePlaylistRepository.findAll();
        for (CollaborativePlaylist collaborativePlaylist : collaborativePlaylists) {
            updateOne(collaborativePlaylist.getId_playlist());
        }
    }

    @GetMapping(path = "/{id}")
    public @ResponseBody void getPlaylist(@PathVariable Long id){

        ////TODO: implement
        Optional<CollaborativePlaylist> optionalCollaborativePlaylist = collaborativePlaylistRepository.findById(id);
    }


    private Track getAlternativeIdentifier(Track track){
        Track newTrack = new Track(track);
        if(!track.hasServiceIdentifier(Platform.SPOTIFY)){
            //Track localTrack = newTracks.
            String id = getApiService(Platform.SPOTIFY).getServiceIdentifierBasedOnIsrc(track.getIsrc());
            if(id==null){
                newTrack.setSpotify_availability(false);
            }{
                newTrack.setSpotify_identifier(id);
                newTrack.setSpotify_availability(true);
            }
        }else{
            newTrack.setSpotify_availability(true);
        }

        if(!track.hasServiceIdentifier(Platform.DEEZER)){
            //Track localTrack = newTracks.
            String id = getApiService(Platform.DEEZER).getServiceIdentifierBasedOnIsrc(track.getIsrc());
            if(id==null){
                newTrack.setDeezer_availability(false);
            }{
                newTrack.setDeezer_identifier(id);
                newTrack.setDeezer_availability(true);
            }
        }else{
            newTrack.setDeezer_availability(true);
        }
        return newTrack;
    }

    /**
     *
     * @param platform
     * @param storedTracks
     * @param remotePlaylistTracks
     * @return
     */
    private List<String> getNewTracksIds(Platform platform, Set<Track> storedTracks, Set<Track> remotePlaylistTracks) {
        List<Track> tracksToAdd = new ArrayList<>(storedTracks);
        tracksToAdd.removeAll(remotePlaylistTracks);

        List<String> tracksIds = new ArrayList<>();

        tracksIds = tracksToAdd.stream().map(track -> {
            if(platform.equals(Platform.SPOTIFY) && track.isSpotify_availability()){
                return track.getSpotify_identifier();
            }
            if(platform.equals(Platform.DEEZER) && track.isDeezer_availability()){
                return track.getDeezer_identifier();
            }
            return null;
        }).collect(Collectors.toList());

        return tracksIds;
    }
}
